### PR TITLE
[SPI-123] - feature/ pull requests title naming conventions

### PR DESCRIPTION
**Pull request by miguelemosreverte**
# Description 
as you can see by the naming of this branch, now branch naming must follow the pattern:
image

### CODE REVIEW

**Comment by testagrossa** [comment]
we talked about having ticket-reference to branch name.
also i want to enforce things at PR level

**Comment by rockit-it** [comment]
> we talked about having ticket-reference to branch name. also i want to enforce things at PR level

I prefer don't use a ticket-reference in the branch name because the association will be part of the description in the PR

**Comment by miguelemosreverte** [comment]
I agree with @Ignacio-Rocca, the ticket is already available at the PR, which allows search:
 Github does retrieve the relevant data upon searching by ticket-id, given that you place the ticket-id on the PR description.

**Comment by testagrossa** [comment]
having the ticket name in branch allows me to quickly understand the product evolution using git ui tools at high level without the need to go explore

**Comment by miguelemosreverte** [comment]
sound reasonable. @Ignacio-Rocca you concur?

**Comment by miguelemosreverte** [comment]
@Franco Testagrossa quick question -- can we ask what is going to be the Jira project preffix?

**Comment by rockit-it** [comment]
> sound reasonable. @Ignacio-Rocca you concur?

For me isn't reasonable because I always delete the branch after merge the PR. I think that franco need to use the dashboard where we have the tickets ( trello, jira, etc ) to see the project advance , and in all tickets we need the reference to the PR , and in all PR the reference to the ticket is a cross reference

Other point is that not always you have a ticket when you are doing something , for example a imagine the hotfix case, I don't want in that moment think in the ticket when my servers are on fire I only want to push my fix

**Comment by miguelemosreverte** [comment]
I agree with @Ignacio-Rocca, Jira is the tool you want @testagrossa

What about putting the [TICKET_ID] in the  PR name?
ie.:
**[JR-145] Updating database**

This in my experience was enough for JIRA to pickup the link automatically, and render it.

@testagrossa @Ignacio-Rocca?

Something like this (for the PR naming)
image

example: 
[JR-123] feature/ add Redis
[JR-124] bugfix/ remove typo on the Redis connection

**Comment by testagrossa** [comment]
lets put the ticket at least on the PR name

**Comment by testagrossa** [comment]
@Ignacio-Rocca when u have multiple branches opened at the same time it is useful dont u think

**Comment by rockit-it** [comment]
> @Ignacio-Rocca when u have multiple branches opened at the same time it is useful dont u think

Yes this can happen but you have the daily report to know the state of my task and after the PR and if you want I can attach my branch in the ticket too. 

The question here @testagrossa I think is: how many times do you enter to a branch of other person and review what commit that person ? If you want to see my progress I always have the option to create a PR in draft state !

**Comment by miguelemosreverte** [comment]
@testagrossa 
@Ignacio-Rocca 

as you can see, now a pull request will not be green lighted until it has the title with the pattern we agreed upon.

Visit here:
https://github.com/Prom3th3us/scala-template-repository/actions

for detailed back and forth between me and the automated tests, where they push me to use the correct pattern.

**Pull request merged**
